fixing aida snaps
cej25/c4Root pull request #145
Opened 2024-04-02 16:15 UTC by Rooitier

- Fixed aida snapshot - it compiles. Nic maybe test to see it works. 
- removing stream/position from bplast raw2cal

2024-04-02 16:24 UTC, cej25 approved these changes

2024-04-04 09:47 UTC, nichubbard requested changes
Scaler snapshots do not work

Info in <TCanvas::Print>: png file aida_scalers.png has been created
Info in <TCanvas::Print>: png file aida_scalers.png has been created
Info in <TCanvas::Print>: png file aida_scalers.png has been created
Info in <TCanvas::Print>: png file aida_scalers.png has been created
Error in <TGraphPainter::PaintGraph>: illegal number of points (0)
Info in <TCanvas::Print>: png file aida_scalers.png has been created
Error in <TGraphPainter::PaintGraph>: illegal number of points (0)
Info in <TCanvas::Print>: png file aida_scalers.png has been created

(Scalers need unique names too)

Decay and Implant work perfectly

2024-04-20 17:41 UTC, Rooitier commented
new changes. hopefully everything is there.

2024-04-20 17:51 UTC, nichubbard approved these changes

2024-04-20 18:33 UTC, merged